djangoproject/djangoproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('university/', include('university.urls')),
    path('admin/', admin.site.urls),
]

djangoproject/university/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:university_id>/', views.university_details, name='university_details'),
    path('student/<int:student_id>/', views.student_details, name='student_details'),
]

djangoproject/university/models.py
from django.db import models


class University(models.Model):
    class Meta:
        verbose_name_plural = 'universities'

    CITY_CHOICES = [
        ('buc', 'Bucharest'),
        ('ias', 'Iași'),
        ('clu', 'Cluj-Napoca'),
    ]
    name = models.CharField(max_length=200)
    city = models.CharField(max_length=3, choices=CITY_CHOICES)

    def __str__(self):
        return f'{self.name} ({self.get_city_display()})'


class Student(models.Model):
    university = models.ForeignKey(University, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_enrolled = models.DateField()

    def __str__(self):
        return f'{self.first_name} {self.last_name} ({self.date_enrolled})'

djangoproject/university/views.py
from django.shortcuts import render, get_object_or_404

from .models import University, Student


def index(request):
    universities = University.objects.all()
    context = {'universities': universities}
    return render(request, 'university/index.html', context)


def university_details(request, university_id):
    university = get_object_or_404(University, pk=university_id)
    context = {'university': university}
    return render(request, 'university/university_details.html', context)


def student_details(request, student_id):
    student = Student.objects.get(pk=student_id)
    context = {'student': student}
    return render(request, 'university/student_details.html', context)

djangoproject/university/templates/university/base.html
<html>
    <head>
        <title>Universities index</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <div class="page-header">
            <h1><a href="{% url 'index' %}">Universities index</a></h1>
        </div>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

djangoproject/university/templates/university/index.html
{% extends 'university/base.html' %}

{% block content %}
    {% if universities %}
        <ul class="list-group">
        {% for university in universities %}
            <li class="list-group-item"><a href="{% url 'university_details' university.id %}">{{ university }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No universities are available.</p>
    {% endif %}
{% endblock %}

djangoproject/university/templates/university/student_details.html
{% extends 'university/base.html' %}

{% block content %}
    <h4>{{ student }}</h4>
{% endblock %}

djangoproject/university/templates/university/university_details.html
{% extends 'university/base.html' %}

{% block content %}
    <h4>{{ university }}</h4>
    <ul class="list-group">
        {% for student in university.student_set.all %}
            <li class="list-group-item"><a href="{% url 'student_details' student.id %}">{{ student }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}